### ISSUE TITLE
Stock Price Bug in Portfolio page

### ISSUE THREAD

**Issue by janevy** [BT3103AppDev1/final-project-l1-final-project-group-12#28]
Cc:

Hi all!

### Describe the Bug

In the portfolio page, we present expected returns and cost of each trade in SGD. However, the prices reflected in Price might not always be in SGD.

### To Reproduce
1. Go to Porfolio page
2. Input an example trade of a stock not listed on SGX
3. Click on add
4. See error on the Price

### Expected Behavior

The price reflected should be in SGD

### Tasks
- [ ] Normalise the stock price of stocks listed outside Singapore to SGD
- [ ] Insert a $ in front of Price

### Acceptance Criteria

When the price reflected on the page is in SGD.

### Screenshots

![image](https://github.com/BT3103AppDev1/final-project-l1-final-project-group-12/assets/92180655/e73c8bf6-10f1-4e35-99ea-0ebd1ea7af71)

Thanks!

**Comment by mengyewgau** [comment]
Closing issue and classifying as blocked
